version: '3.8'

services:
  api:
    container_name: api-server
    build: ./server
    ports:
      - 80:8080
    depends_on:
      - postgresql
  postgresql:
    container_name: postgresql
    build: ./postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    restart: always
volumes:
  db-store:
