FROM ubuntu:22.04

RUN apt-get update && apt-get install -y curl
RUN apt-get install -y build-essential 
RUN apt-get install -y pkg-config
RUN apt-get install -y libssl-dev

# Rust install
ENV RUST_HOME /usr/local/lib/rust
ENV RUSTUP_HOME ${RUST_HOME}/rustup
ENV CARGO_HOME ${RUST_HOME}/cargo
RUN mkdir /usr/local/lib/rust && \
    chmod 0755 $RUST_HOME
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > ${RUST_HOME}/rustup.sh \
    && chmod +x ${RUST_HOME}/rustup.sh \
    && ${RUST_HOME}/rustup.sh -y --default-toolchain nightly --no-modify-path
ENV PATH $PATH:$CARGO_HOME/bin

WORKDIR /tmp

COPY . /tmp/

CMD [ "cargo", "run", "--release" ]